# Generated by Django 4.0.3 on 2022-03-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_delete_about_delete_address_delete_certification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myself', models.TextField(max_length=200)),
            ],
        ),
    ]
