# Generated by Django 4.0.3 on 2022-03-28 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_address_certification_contact_education_experience_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='P_Skills',
            new_name='ProfileSkills',
        ),
        migrations.RenameField(
            model_name='profileskills',
            old_name='p_skills',
            new_name='p_skill',
        ),
    ]
