# Generated by Django 4.0.3 on 2022-03-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_rename_p_skills_profileskills_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='myself',
            field=models.TextField(max_length=2000),
        ),
    ]
