# Generated by Django 4.0.3 on 2022-03-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_alter_education_degree_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='certification',
            name='full_name',
            field=models.CharField(max_length=100),
        ),
    ]
