# Generated by Django 4.0.3 on 2022-03-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_alter_address_address_alter_address_phone_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_image', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
